### PR TITLE
feat: support for Ubuntu 22.04

### LINKED ISSUE #61: Need support Ubuntu 22
Ubuntu 22.04 has been released. Thanks.
https://ubuntu.com/blog/ubuntu-22-04-lts-released

### PR DESCRIPTION
**Pull request by manusa**
fix #61

### CODE REVIEW

**Comment by pan3793** [comment]
Hi, what's the status of this PR? I see the CI only failed w/ obsolete K8s versions(1.17 & 1.18), can I expect them will work on Ubuntu 22.04 or just drop them on the new Ubuntu platform?

**Comment by manusa** [comment]
> Hi, what's the status of this PR? I see the CI only failed w/ obsolete K8s versions(1.17 & 1.18), can I expect them will work on Ubuntu 22.04 or just drop them on the new Ubuntu platform?


Apparently everything should work fine with newer versions of K8s. I was planning on getting a VM with Ubuntu 22 and make further improvements, but didn't get the time.

I think I'll just merge and add a warning note for earlier versions.

**Comment by manusa** [comment]
> Hi, what's the status of this PR? I see the CI only failed w/ obsolete K8s versions(1.17 & 1.18), can I expect them will work on Ubuntu 22.04 or just drop them on the new Ubuntu platform?


I just released [v2.7.0](https://github.com/manusa/actions-setup-minikube/releases/tag/v2.7.0), it would be great to have your feedback :pray:

**Comment by pan3793** [comment]
Thanks @manusa, cc @deadwind4

**Pull request merged**
